# Generated by Django 3.2.6 on 2021-09-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('wip', 'WIP'), ('d', 'DONE'), ('a', 'ARCHIVED')], default='wip', max_length=3),
        ),
    ]
