# Generated by Django 3.2.6 on 2021-09-14 22:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0006_task_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_working_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='spent_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
