# Generated by Django 3.2.6 on 2021-09-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0009_tag_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='task',
            field=models.ManyToManyField(related_name='tag_task', to='task_app.Task'),
        ),
    ]
