# Generated by Django 3.2.6 on 2021-09-29 02:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_app', '0011_auto_20210925_1257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('author', 'name')},
        ),
    ]
