# Generated by Django 3.2.6 on 2021-10-16 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0012_alter_tag_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
