# Generated by Django 3.2.6 on 2021-09-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('b', 'BACKLOG'), ('bb', 'BOTTOM BACKLOG'), ('wip', 'WIP'), ('d', 'DONE'), ('a', 'ARCHIVED')], default='b', max_length=3),
        ),
    ]
